on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: shiny

jobs:
  shiny:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: '3.6.1'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
            install.packages(c("shiny", "rsconnect", "devtools"), type = "binary")
            library(devtools)
            devtools::install_github("JGCRI/hectorui")
        shell: Rscript {0}

      - name: Push to shiny.io
        run: |

          Rscript -e "rsconnect::setAccountInfo(name='jgcri', token= '${{secrets.SHINYAPPS_TOKEN}}' , secret= '${{secrets.SHINYAPPS_SECRET}}')"
          Rscript -e "rsconnect::deployApp(appDir = system.file('shinyApp', package = 'hectorui'), appName = 'HectorUI')"
