on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: shiny

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
            install.packages(c("shiny", "rsconnect", "devtools"), type = "binary")
            library(devtools)
            devtools::install_github("JGCRI/hectorui")
        shell: Rscript {0}

      - name: Push to shiny.io
        run: |
          Rscript -e "setwd('/Users/runner/work/hectorui/inst/shinyApp')"
          Rscript -e "rsconnect::setAccountInfo(name='jgcri', token= '${{secrets.SHINYAPPS_TOKEN}}' , secret= '${{secrets.SHINYAPPS_SECRET}}')"
          Rscript -e "rsconnect::deployApp(appName = 'HectorUI')"
