on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: shiny

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='jgcri', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'HectorUI')"
